### ISSUE TITLE
[Docs] Create smp documentation google doc. 

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/service-mesh-performance#72]
**Current State:**
The Service Mesh Performance has no google doc for additional reference

**Desired State:**
create a reference google doc for service mesh and add to the down part of the doc README.md for additional reference. You can recreate this meshery doc https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit

---
**Contributor Resources**
- [Service Mesh Performance documentation site](https://meshery.layer5.io/docs/)
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance-specification/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by chandrashritii** [comment]
@PluckyPrecious This is a really good idea. Two issues - 
- The Meshery documentation doc cannot exactly be regurgitated here because the SMP project has certain features and implementations which should be highlighted in the documentation. 
- The [smp-spec.io](https://smp-spec.io/) site has a very different (much more basic) layout than the [meshery.io](https://meshery.io/) site. We can source the layout details from the original [layout doc](https://docs.google.com/document/d/1uorBXRzZemBMAcl6I9jf8TNxbiUCpysbL9uhRVlrOM0/edit?usp=sharing).

I already have a basic template and will be creating a write up for the documentation but we'll need to go through it properly and set up the documentation. This issue can be closed for now.

**Comment by chandrashritii** [comment]
Thanks for the idea @PluckyPrecious 🎈 We will come up with a better implementation process for this. Let's get you on to better issues.
